server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/retoextra
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"